services:
  - type: web
    name: bx3v19
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APIFOOTBALL_KEY
        value: 9ee71b3b8805a94dfad5a819f28f2281
      - key: ODDS_API_KEY
        value: 11f2b69ab3b9f769579047976d30498c
      - key: FOOTBALLDATA_KEY
        value: jMeMekq6cinJindtlF21Cx4EmoxwfZOhpIPJLaNamWmozxTqiRAJkN0EiEBR
      - key: SPORTMONKS_KEY
        value: v139voCJIKSknpdr1c6BQ4K55IHDaVSmYro00RKPyChOx2Vn4ZQs1mEHPHQB
      - key: BX3_SECRET
        value: BX3FamilleEtoh2026SecretKey
    plan: free
    region: frankfurt
